### ISSUE TITLE
Horizontal Scrolling at Media Query Breakpoint

### ISSUE THREAD

**Issue by ryansoeder** [hamzafoy/hamzafoy.github.io#1]
When the window is made wider, the width of the Google Form overflows the margins of Tertiary Column, causing x-scrolling.

**Comment by hamzafoy** [comment]
> When the window is made wider, the width of the Google Form overflows the margins of Tertiary Column, causing x-scrolling.

Thank you Ryan! I incorporated your suggested changes!
